workflows:
  build_android:
    name: Build Android APK
    environment:
      vars:
        ANDROID_HOME: /opt/android-sdk-linux
    scripts:
      - name: Set Java 8
        script: export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 && export PATH=$JAVA_HOME/bin:$PATH
      - name: Install dependencies
        script: npm install
      - name: Build APK
        script: export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 && export PATH=$JAVA_HOME/bin:$PATH && ns build android --release
    artifacts:
      - platforms/android/app/build/outputs/**/*.apk
