workflows:
  build_android:
    name: Build Android APK
    environment:
      vars:
        ANDROID_HOME: /opt/android-sdk-linux
        JAVA_HOME: /opt/java/openjdk
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build APK
        script: ns build android --release
    artifacts:
      - platforms/android/app/build/outputs/**/*.apk
